
name: Hola mundo
on:
  push:
    branches: main
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    outputs: 
      salida: ${{ steps.imprimir.outputs.respuesta}}
    steps:
    - name: Imprimir 
      env:
        MI_VARIABLE: Hola mundo
      run: echo "::set-output name=respuesta::${MI.VARIABLE}"
