
name: Pruebas unitarias
on:
  push:
    branches: main
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: instalando ambientes de desarrollo
      run: python -m venv virtual
    - name: cargando archivo de requerimientos
      run: pip install -r requirements.txt
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    
      with:
          python-version: '3.7'
    - name: Correr pruebas
      id: correr-pruebas
      
      run: python -m unittest -v test/test_persona.py
